### ISSUE TITLE
Robotics

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/subject-ontology#11]
Recently a user submitted the term "Robot". Although it is not required as the record itself is not within FAIRsharing's remit, it made me re-evaluate our discipline/subject term in this area, 'Automation, Control Systems, Robotics, Mechatronics'. We have a standing policy of trying to separate out concepts that were grouped together in the re3data subject headings, though we haven't had time to check all disciplines.

Should we consider separating out these four distinct subjects, making them sibling classes and providing appropriate definitions, @Drosophilic?

**Comment by allysonlister** [comment]
I will find definitions for all of them and then @Drosophilic and I will re-evaluate to see which are suitable as synonyms and which should be new classes.

**Comment by allysonlister** [comment]
See definitions for all 4 terms below.

From the definitions below, I suggest that we simply rename the class _Robotics_. Synonyms would be Mechatronics, Mechatronics Engineering. Definition - use _Robotics_ definition below.

I actually suggest that Automation and Control Systems are both DRAO terms. As no records within FAIRsharing contain these terms yet, I suggest that we do not add them to DRAO at this stage. If @Drosophilic thinks it appropriate, a backburner issue can be raised on the DRAO tracker which can reference this decision.

Robotics: Robotics is an interdisciplinary branch of engineering and science that deals with the design, construction, operation, and use of robots, as well as computer systems for their control, sensory feedback, and information processing. [AL, modified from Wikipedia https://en.wikipedia.org/wiki/Robotics, accessed 26.11.18]

Mechatronics: Mechatronics is a multidisciplinary branch of engineering that focuses on the engineering of both electrical and mechanical systems, and also includes a combination of robotics, electronics, computer, telecommunications, systems, control, and product engineering. The intention of mechatronics is to produce a design solution that unifies each of these various subfields. [AL, modified from Wikipedia https://en.wikipedia.org/wiki/Mechatronics, accessed 26.11.18]
_Note: this would have a synonym of mechatronics engineering_, and a note in the wikipedia entry states that _Many people treat mechatronics as a modern buzzword synonymous with robotics and electromechanical engineering_ so we may be just as well making this a synonym of Robotics.

Automation: Automation is the action or process of introducing automatic equipment or devices into a manufacturing or other process or facility; (also) the fact of making something (as a system, device, etc.) automatic. [OED, accessed 26.11.18]

Control Systems: Control systems are the means by which a variable quantity or set of variable quantities is made to conform to a prescribed norm. A control system either holds the values of the controlled quantities constant or causes them to vary in a prescribed way. It may be operated by electricity, by mechanical means, by fluid pressure (liquid or gas), or by a combination of means. When a computer is involved in the control circuit, it is usually more convenient to operate all of the control systems electrically, although intermixtures are fairly common. [AL, modified from Encyclopaedia Britannica https://www.britannica.com/technology/control-system, accessed 26.11.18]

**Comment by allysonlister** [comment]
@Drosophilic Please may I have your comments on this :)

**Comment by Drosophilic** [comment]
I agree 100%. I particularly like the Robotics definition.
