### ISSUE TITLE
Meteorology

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/subject-ontology#12]
Requested by https://fairsharing.org/bsg-s001321/ and could be used in future. We have climate as a domain (not a discipline), and SRAO also has Atmospheric Science.

OMIT (https://www.ebi.ac.uk/ols/ontologies/omit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FOMIT_0026522) suggests it as a child of both Physics and Earth Sciences. I would be happy to place it within SRAO as a child of both Physics and Atmospheric Science.

**Comment by Drosophilic** [comment]
Sounds good!
