### ISSUE TITLE
Image Processing

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/subject-ontology#13]
https://fairsharing.org/biodbcore-001189/ has requested Image Processing. We already have 'Artificial Intelligence, Image and Language Processing'. Would you like me to split this class? Currently the hierarchy is 

Artificial Intelligence, Image and Language Processing
-- Data visualization
-- Machine learning
-- Natural Language Processing

Updated, it could be

Lanugage Processing === Natural Language Processing (specifically, we can decide if these classes could be merged)
Image Processing
-- Data visualization
Artificial Intelligence
-- Machine learning

I realize there is some overlap here, but where necessary we could have multiple parents.

**Comment by Drosophilic** [comment]
Most of these terms are quite specific and perhaps belong in DRAO rather than SRAO. We need to define them carefully. As is stands the current suggested hierarchy is wrong. 

This ticket has been moved to DRAO.

**Comment by allysonlister** [comment]
We haven't made any changes to the top-level term yet, so reopening this

**Comment by allysonlister** [comment]
Please note that 'natural language processing' is present both in SRAO and DRAO and we need to refactor it out of SRAO.

**Comment by allysonlister** [comment]
The current hierarchy for these terms within SRAO, after all the changes happening as a result of #19, is as follows:
![cs hierarchy](https://user-images.githubusercontent.com/143586/58129505-c3a26980-7c11-11e9-8b2b-aa1fcb5b93c5.png)
@Drosophilic can either let me know what further changes he would like, or he can close this ticket. :-) thanks!

**Comment by allysonlister** [comment]
I can't recall if we decided to do any further work on this, @Drosophilic ? :)

**Comment by Drosophilic** [comment]
I think it's fine to leave this as is for now.
