### ISSUE TITLE
FAIRsharing SRAO annotations

### ISSUE THREAD

**Issue by Drosophilic** [FAIRsharing/subject-ontology#14]
We need to think about how we annotate records with the new SRAO field. Many records are annotated with multiple terms, some of which have a child_of relationship between them (e.g. Life Science -> Biomedical Science).

We need to decide whether we restrict annotation to the most precise term or we include all parent terms on the record as well.

I appreciate this isn't strictly an Ontology issue, more a FAIRsharing-specific issue, but given it will affect annotation and may affect the structure and definitions within SRAO, I thought to place it here in the first instance.

**Comment by Drosophilic** [comment]
We will discuss this in person with Susanna at our meeting in Oxford in January.

**Comment by allysonlister** [comment]
We should only annotate with the most precise term.
