### ISSUE TITLE
Subject agnostic: annotation choices and placement within SRAO

### ISSUE THREAD

**Issue by Drosophilic** [FAIRsharing/subject-ontology#15]
We used to have a user-defined tag called 'General Purpose', which was used for standards that were applicable to every subject. This has now disappeared. We need to consider whether it is useful to reinstate this term. We also need to ensure that no data is lost when a term such as this disappears, e.g. new terms are created and all records annotated with the original terms are reviewed and new user tags are added if necessary.

**Comment by allysonlister** [comment]
Please note that this tag hasn't been deleted, but has been put in the "Needs Discussion" part of the user-defined tags list (not currently stored in this repository). It is therefore a User-defined tag right now, and not an ontology term. I agree that we need to decide where it goes, long term, and indeed if it should remain.

**Comment by Drosophilic** [comment]
Yes, by 'loss' I meant from the ontology. We should discuss this at the next call.

**Comment by Drosophilic** [comment]
We will discuss this in person with Susanna at our meeting in Oxford in January.

**Comment by Drosophilic** [comment]
We have decided to add 'General Purpose' as a high level term alongside Natural Sciences, Humanities and so on. We still need to decide how we will annotate this term. For example, should XML be annotated with General Purpose alone, or also Computer Science? How will we handle Computer Science formats when many could legitimately be considered 'General Purpose'?

**Comment by allysonlister** [comment]
Please note that if we add this as a sibling term to the other top-level terms in SRAO it will mean something semantically different from if it is *the* top level term.
* sibling term: will not have any other terms as part of its hierarchy; will be standalone. Benefits: it can mean something _beyond_ just "all research areas" and could instead mean "all types of digital objects", for example
* top-level term: we would be only using it to describe all research areas together.

Whatever the choice, it will have consequences both for users of SRAO and how it is implemented within FAIRsharing.

**Comment by allysonlister** [comment]
I have reviewed all uses of "General Purpose" within FAIRsharing and am ready to incorporate Subject Agnostic within SRAO.

**Comment by allysonlister** [comment]
I have reviewed the very few (<30 records) instances where all three top-level terms have been included, and updated their tag annotation accordingly. This does mean that between now and the incorporation of this SRAO release, there will be (in some cases) no subject tags, but this is only temporary.
