### ISSUE TITLE
Natural History term

### ISSUE THREAD

**Issue by Drosophilic** [FAIRsharing/subject-ontology#17]
We currently have 'Natural History' as a child term of 'Natural Sciences'

It has the following definition:
"The systematic account of natural phenomena; in medicine, the elucidation and description of disease progress."

I'm not sure this definition is correct. I would say Natural History should go under Natural Sciences as:
"the scientific study of animals or plants, especially as concerned with observation rather than experiment, and presented in popular form." 

and we should perhaps have another term called 'Patient Natural History', with the definition:
"The systematic account of natural phenomena; in medicine, the elucidation and description of disease progress."

Which should be a child term of Medicine.

**Comment by Drosophilic** [comment]
After discussion:
Life Sciences:
   - Natural History (definition from Wikipedia)
Medicine
   - Patient History  (retain NCIT label)

**Comment by allysonlister** [comment]
Two questions for @Drosophilic 

1. Is Patient History really a subject area, or is it more suited to DRAO? If so, do we need to add it to DRAO at the moment (or preferentially put them on the backburner)? The current usages of this class are not as Patient History so this concept is not currently used within FAIRsharing. (see also question 2 below)

2. The 4 records tagged with 'Natural History' are all using the 'traditional', non-medical definition of Natural History. This is about to get a new IRI - we should check how FAIRsharing would deal with such a change behind the scenes.

**Comment by Drosophilic** [comment]
OK, I see your point. Let's move Patient History to DRAO (as a backburner issue).

Yes, the process should also be documented internally.

**Comment by allysonlister** [comment]
I have changed the IRI for Natural History from http://purl.obolibrary.org/obo/NCIT_C16147 to http://www.fairsharing.org/ontology/SRAO_0000291. I have also added a definition.

**Comment by allysonlister** [comment]
FYI: There are 4 records with this tag (https://fairsharing.org/FAIRsharing.c2wkqx, https://fairsharing.org/FAIRsharing.d21jc4, https://fairsharing.org/FAIRsharing.anxqkv, https://fairsharing.org/FAIRsharing.3wwc0m). All should retain the tag with the new IRI as are all using the non-medical definition of Natural History.
