### ISSUE TITLE
New URI for Pathology and Forensic Medicine

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/subject-ontology#18]
Currently Pathology and Forensic Medicine' has an EDAM URI (topic_0634)which originally had the label 'Disease'. This isn't really a good match for this subject/discipline, especially as DRAO already has 'disease' via EFO. We can either

1. Simply remove the 'disease' synonym from SRAO and leave the URI, or
2. replace it with one or more URIs, e.g. Pathology (http://purl.obolibrary.org/obo/NCIT_C18189) and Forensic Medicine (http://purl.obolibrary.org/obo/NCIT_C16591).

I suggest choice 2 as this gets rid of the 'and'.

**Comment by Drosophilic** [comment]
I agree, let's go for number 2.

**Comment by allysonlister** [comment]
The change in IRIs have been as follows:
1. Deletion of http://edamontology.org/topic_0634
2. Addition of http://purl.obolibrary.org/obo/NCIT_C18189 - Pathology
3. Addition of http://purl.obolibrary.org/obo/NCIT_C16591 - Forensic Medicine

There are 4 FAIRsharing records with this tag. I suggest that all 4 maintain the Pathology tag, but don't need the Forensic Medicine tag.

https://fairsharing.org/biodbcore-001087/ 
https://fairsharing.org/FAIRsharing.95n1ns
https://fairsharing.org/FAIRsharing.z4xpxx 
https://fairsharing.org/FAIRsharing.83wDfe

I'll proceed in this way (via @Zigur and appropriate checks on IRI changes via our new internal documentation) unless @Drosophilic says otherwise.
