### ISSUE TITLE
Removing instances of "and"

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/subject-ontology#19]
Some labels within SRAO contain the word "and" - these terms came from re3data. We would like to refactor these into a more consistent naming scheme.

**Comment by Drosophilic** [comment]
This will most likely involve the splitting of these terms into one or more term. Where this is the case, we need to ensure that not only do the hierarchy and definitions remain accurate, but that the annotation of records with these terms also remains appropriate.

**Comment by allysonlister** [comment]
If we are still planning to have a new release for @Zigur for 7 December, this should be postponed until the release after it, as it will take some discussion between me and @Drosophilic, who is away most of this week.

**Comment by allysonlister** [comment]
I have begun work on this in the development files. Commits will reference this issue as composite terms are resolved. Please note that the re2data composite labels will be retained in one of the resulting split classes, via the "re3data alternative term" property.

**Comment by allysonlister** [comment]
This is complete other than the 'Rural and Agricultural Sociology' term. We had agreed to split and keep both Rural Sociology and Agricultural Sociology. However, looking more deeply into this, there doesn't seem to be any definition available - or websites devoted to - agricultural sociology. I suggest we just retain Rural Sociology for now. If AgroVoc doesn't include Agricultural Sociology as a separate term, is it worth us retaining it? What do you think @Drosophilic ?

**Comment by Drosophilic** [comment]
Perhaps we make an exception for this term, as on closer inspection I think the two aspects are related (e.g. https://www.annualreviews.org/doi/abs/10.1146/annurev.so.09.080183.000435)
