### ISSUE TITLE
Construction Engineering and Architecture: Hierarchy modifications

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/subject-ontology#2]
As things stand, this hierarchy (which comes directly from re3data) is complicated and hard to understand. There are many compound classes (i.e. which include a list or "and"). A user who wishes to simply add "Architecture" has to choose from two very odd classes, and there is no "Civil Engineering" option. Civil Engineering needs to be added to SRAO as part of #1 and therefore this is an opportune time to clear up the existing hierarchy.

Please can @Drosophilic look over the suggested changes.

Current Hierarchy:

Engineering Science
++Construction Engineering and Architecture
++++Applied Mechanics, Statics and Dynamics
++++Architecture, Building and Construction History, Sustainable Building Technology, Building Design
++++Construction Material Sciences, Chemistry, Building Physics
++++Geotechnics, Hydraulic Engineering
++++Structural Engineering, Building Informatics, Construction Operation
++++Urbanism, Spatial Planning, Transportation and Infrastructure Planning, Landscape Planning

Proposed Hierarchy:

Engineering Science
++Civil Engineering 
++++Construction Engineering
++++++Construction Material Sciences: recommend replace with existing class Materials Science, see below.
++++++Building Physics
++++++Geotechnics
++++++Hydraulic Engineering
++++++Structural Engineering
++++++Building Informatics
++++++Construction Operation: recommend removal, see below.
++++++Urban Planning
++++++Transportation Planning
++++++Landscape Planning
++++Architecture (split existing class): Use existing definition by PAM
++++++Construction History
++++++Sustainable Building Technology
++++++Building Design

Definitions and IRIs of above classes:
* Civil Engineering: (http://aims.fao.org/aos/agrovoc/c_1648): definition "Civil engineering is the branch of engineering that deals with the design, construction, and maintenance of works of public utility, especially those relating to social infrastructure. [Oxford English Dictionary, AL 08.05.18]"
* Construction Engineering: Use existing definition by PAM
* Construction Material Sciences: recommend that we remove this term, as the definition we already have for "Materials Science" includes construction. Also recommend that we add a new parent term to "Materials Science" of either "Civil Engineering" or "Construction Engineering", depending on what @Drosophilic would prefer.
* Building Physics: Change name to "Building Engineering Physics" to match what appears to be common usage within the community. Definition: "Building Engineering Physics investigates the areas of natural science that relate to the energy performance of buildings and their indoor and outdoor environments. The understanding and application of Building Engineering Physics allows us to design and construct high performance buildings which are comfortable and functional, yet use natural resources efficiently and minimise the environmental impacts of their construction and operation. It is related to Architecture, Structural Engineering and Building Services Engineering. [https://www.raeng.org.uk/news/news-releases/2010/January/engineering-a-low-carbon-built-environment, AL 08.05.18]"
* Geotechnics: def "The application of science and technology to the management and utilization of the earth's physical resources. [Oxford English Dictionary, AL 08.05.18]"
* Hydraulic Engineering: http://aims.fao.org/aos/agrovoc/c_3713 definition: "Hydraulic engineering is the application of the principles of fluid mechanics to problems dealing with the collection, storage, control, transport, regulation, measurement, and use of water. [Wikipedia https://en.wikipedia.org/wiki/Hydraulic_engineering, AL 08.05.18]"
* Structural Engineering: definition: "Structural Engineering is the branch of civil engineering concerned with the analysis and design of large buildings and load-bearing structures. [Oxford English Dictionary, 08.15.18]"
* Building Informatics: I cannot find a suitable definition. Shall we postpone the definition for a later date, or remove the class altogether if it is a true edge case for our users?
* Construction Operation: it is unclear what is meant by this phrase within re3data. Does not seem to be a discipline/subject area. Recommend removing it altogether.
* Urban Planning: Due to the definitions of Urbanism and Spatial Planning, it is recommended that these 3 terms be consolidated into one term (Urban Planning, http://aims.fao.org/aos/agrovoc/c_37948) as that provides an appropriate level of detail for our users: def "Urban Planning is the planning and regulation of building, development, reconstruction, etc., in an urban area [Oxford English Dictionary, AL 08.05.18]"
* Transportation and Infrastructure Planning: to get rid of the "and", we rename to "Transportation Planning". def "Transport Planning is the process of defining future policies, goals, investments, and designs to prepare for future needs to move people and goods to destinations. It is involved with the evaluation, assessment, design, and siting of transport facilities (generally streets, highways, bike lanes, and public transport lines). [Wikipedia https://en.wikipedia.org/wiki/Transportation_planning, AL 08.005.18]"
* Landscape Planning: def "Landscape Planning is concerned with developing landscaping amongst competing land uses while protecting natural processes and significant cultural and natural resources. [Wikipedia https://en.wikipedia.org/wiki/Landscape_planning, AL 08.05.18]
* Architecture (split existing class): Use existing definition by PAM
* Building and Construction History: rename to both remove the "and" and align with discovered community usage to "Construction History". def "Construction  History is the history of how not only buildings are constructed, but also the construction of civil engineering and infrastructure. As such, it includes bridges, sewers, power stations, mills etc. as well as conventional buildings. In particular, the subject focuses on how these objects were constructed. [Adapted from http://www.constructionhistory.co.uk/about-construction-history-society/construction-history/, AL 08.05.18]"
* Sustainable Building Technology: add synonym "Green Building Technology". def "Sustainable Building Technology is the application of processes that are environmentally responsible and resource-efficient throughout a building's life-cycle: from planning to design, construction, operation, maintenance, renovation, and demolition. This requires close cooperation of the contractor, the architects, the engineers, and the client at all project stages. [Wikipedia https://en.wikipedia.org/wiki/Green_building, AL 08.05.18"
* Building Design: def "Building design refers to the broadly based architectural, engineering and technical applications to the design of buildings. [Wikipedia https://en.wikipedia.org/wiki/Building_design, AL 08.05.18]

**Comment by Drosophilic** [comment]
All look good.
"Materials Science" - perhaps under construction engineering makes more sense than civil engineering.

**Comment by allysonlister** [comment]
Great, thanks!
