### ISSUE TITLE
Biomedical Science / Health Science

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/subject-ontology#20]
One of the synonyms provided by EDAM for its term _Biomedical Science_ is _Health Science_. This is an issue for SRAO because we need (and already have) a sibling term called _Health Science_. As synonyms are also indexed and searchable within FAIRsharing, then this could result in false positive hits in search results. We have been aware of this issue since the beginning of this year, but have now begun to codify our methods for dealing with it, so it is an appropriate time to sort this out. I recommend either:

1. Adding 'Health Science' to our manually-updated list at https://github.com/FAIRsharing/subject-ontology/blob/master/SRAO-alt-term-rejects.txt - this is less than ideal, as it means an extra step in the release of SRAO and I would like to be able to remove this list altogether in the near future, or
2. Change the IRI of _Biomedical Science_, for example to NCIT's http://purl.obolibrary.org/obo/NCIT_C15188 (see also https://www.ebi.ac.uk/ols/ontologies/ncit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_C15188). In this case we could keep NCIT's original label (_Biomedical Research_) as a synonym.

I prefer number 2.

**Comment by Drosophilic** [comment]
I also prefer no. 2.
