### ISSUE TITLE
Chemistry

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/subject-ontology#21]
Two of the synonyms provided by EDAM for its term _Chemistry_ is _Organic Chemistry_ and _Physical Chemistry_, among others. This conflates multiple disciplines of Chemistry, and is also an issue for SRAO because we need (and already have) child terms _Organic Chemistry_ and _Physical and Theoretical Chemistry_ (the quality of the label of this latter term is more of an issue for #19 rather than here). As synonyms are also indexed and searchable within FAIRsharing, then this could result in false positive hits in search results. We have been aware of this issue since the beginning of this year, and I have been using https://github.com/FAIRsharing/subject-ontology/blob/master/SRAO-alt-term-rejects.txt to remind me to remove them, but this isn't ideal. Our options are:

1. Keeping things as they are and using the rejects list mentioned above  - this is less than ideal, as it means an extra step in the release of SRAO and I would like to be able to remove this list altogether in the near future, or
2. Change the IRI of _Chemistry_, for example to NCIT's http://purl.obolibrary.org/obo/NCIT_C16414 (see also https://www.ebi.ac.uk/ols/ontologies/ncit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_C16414). As it doesn't have such a wide range of synonyms, no further work would need to be done and we would be able to remove all synonyms from the rejects list.

I prefer number 2.

**Comment by Drosophilic** [comment]
I also prefer no. 2
