### ISSUE TITLE
Ontology and terminology

### ISSUE THREAD

**Issue by Drosophilic** [FAIRsharing/subject-ontology#24]
We need to consider whether this is a useful term or not, considering we have a standard subtype (terminologies) which covers these types of standard.

**Comment by Drosophilic** [comment]
This term can be legitimately used when referring to a database of ontologies, e.g. OBO Foundry. However, as is, it is easy to confuse this term with the standard subtype of the same name. We therefore need to think of a different term to capture the same (or roughly the same) meaning. 

For example:
Knowledge representation
Semantics
Semantic web
Structured Hierarchy

**Comment by Drosophilic** [comment]
Note, we will (of course) have to revisit all records annotated with this term, as many ontologies have been annotated with this term inappropriately. We will need to review them one-by-one.

**Comment by Drosophilic** [comment]
Another one to consider in this discussion is the term 'Taxonomy'.

**Comment by allysonlister** [comment]
I suggest that we retain this tag, but remove it from all currently existing terminology artefact records: https://beta.fairsharing.org/search?fairsharingRegistry=Standard&subjects=ontology%2520and%2520terminology&page=1&recordType=terminology_artefact As such, an appropriate FAIRsharing ticket has been created.

While I would like to rename this term, I am unsure about what to rename it as, so I think we should simply fix the curation and then revisit this at some later data with regards to refactoring the class.
