### ISSUE TITLE
Use of Data submission, annotation and curation

### ISSUE THREAD

**Issue by Drosophilic** [FAIRsharing/subject-ontology#26]
I'm not sure if we are using this term appropriately. Surely it could be added to most databases?

**Comment by allysonlister** [comment]
As with many of these things, I feel we should either 1) remove it altogether as it is too broad, or 2) heavily restrict its use (as we are considering doing with #24) via our curation guidelines such that it is only applicable to those resources whose research area *is* data curation. In such cases, we would want to use this tag for something like a guideline or standard on how to curate data, but not for a database which has curation.

Case 2 does seem like a bit of an edge case and, therefore, we may prefer to remove this term. We should follow whatever precedent is set by #24 and https://github.com/FAIRsharing/domain-ontology/issues/6

**Comment by allysonlister** [comment]
We have decided to keep Ontology & Terminology in #24 but clean up the annotation. This one is even broader than O&T is, and I can't see what additional value we get from it beyond what we have in the database attributes section of a database record.

I recommend removing this tag, especially as it is only present in 46 records: https://beta.fairsharing.org/search?subjects=data%2520submission%252C%2520annotation%2520and%2520curation&page=1
