### ISSUE TITLE
Declined User Submissions: May 2018

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/subject-ontology#3]
This issue lists all declined user submissions for SRAO in May 2018, and the reasons that the tags are not within SRAO's remit. If the tag is appropriate for our User Tags, this is noted.

This issue can be closed when all terms for this month are resolved. Most do not require changes to the ontology, but curation changes within the repository.

Submitted for https://fairsharing.org/biodbcore-001020 (modifications to these terms within the record is awaiting resolution of #2)
- [x] Technology - this term is too generic
- [x] Applied Sciences - this term is too generic
- [x] industrial design engineering - replaced with existing term from #2 , "Building Design"
- [x] architecture and built environment - replace with "Architecture" from #2
- [ ] policy and management - delete and suggest that the user provides a definition so we can properly include it.
- [x] geoscience - replace with Earth Sciences as Geosciences is an alternative term. This needs to be moved out to the broader FAIRsharing site team, as it is a term that needs aligning properly within the pre-SRAO domain tags as well.

Submitted to records that will most likely be deleted:
- [x] vibration
- [x] active control
- [x] matlab
- [x] machine learning (this is the only instance, can be added back if more people request it)
- [x] packing industries
- [x] Energy (too generic)
- [x] Synthetic Aperture Interferometric Radiometer
- [x] Restoration
- [x] Functional analysis (too generic and too close - though not identical - to Function Analysis)

**Comment by Drosophilic** [comment]
These are all fine but I'd like to keep Machine Learning. I think it should belong in DRAO ;)

**Comment by allysonlister** [comment]
I've done all changes except for this:

> policy and management - delete and suggest that the user provides a definition so we can properly include it.

Shall I contact them about this now, @Drosophilic ?

**Comment by Drosophilic** [comment]
Yes please! (or I can)

**Comment by allysonlister** [comment]
Actually, as it's now so late in the day, and I'm on vacation tomorrow - please could you contact them? Thanks very much @Drosophilic !

**Comment by allysonlister** [comment]
@Drosophilic have you contacted them, or should I do it? Thanks!

**Comment by Drosophilic** [comment]
No, I haven't contacted. Could you please?

**Comment by allysonlister** [comment]
User confirmed on 27.6.18 that we did not need to retain 'Policy and Management'.
