### ISSUE TITLE
Care in the community / Community Care

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/subject-ontology#30]
We currently have Social Medicine (Social Medicine is a branch of science concerned with social and economic aspects of health, disease, and medical care [Adapted from OED, AL 1.5.2019]), but we need to investigate how community care relates to Social Medicine, and if another term is warranted.

**Comment by allysonlister** [comment]
While there is supportive care (NCIT, https://www.ebi.ac.uk/ols/ontologies/ncit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_C15747) it is specific to cancer treatment. 

There is a good definition of what we are looking to describe here: "Community care services are intended to help people who need care and support to live with dignity and independence in the community and to avoid social isolation. The services are aimed at the elderly and those who have mental illness, learning disability and physical disability. The main aim in providing community care services is to enable people to remain living in their own homes and to retain as much independence as possible, avoiding social isolation. " at https://patient.info/doctor/community-care but I can't find a suitable IRI. We would have to mint an IRI if we want this.

If we want this term, I suggest we have it as a child of Social Medicine. @Drosophilic what are your thoughts?

**Comment by Drosophilic** [comment]
I think that we should make our own IRI using your definition and hierarchy.
