### ISSUE TITLE
Data Identity and Mapping

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/subject-ontology#33]
As part of #19 we need to resolve this. Pete and I agreed that it was not required within SRAO. However, @Drosophilic please could you confirm whether we should completely delete it, or move it to DRAO? We currently are using it in all FAIR Metrics records (13).

**Comment by Drosophilic** [comment]
I think these should be merged into DRAO.

**Comment by allysonlister** [comment]
We will need to release a new point release of DRAO at the same time as SRAO so that the class doesn't go missing from FAIRsharing.

**Comment by allysonlister** [comment]
I have added comments for @Drosophilic 's attention in the DRAO ticket.
