### ISSUE TITLE
Health Sciences

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/subject-ontology#34]
We currently have Health Sciences as a near top-level term under Natural Sciences. I recorded that it has come from NCIT only, which means that it was a term already used in FAIRsharing. However, it only has one child (Clinical Immunology). We should investigate whether or not we really need this term, or if it can be subsumed within another subject (biomedical sciences? Medicine?). If we do need it, we should investigate if any other subjects should be added to its hierarchy.

**Comment by allysonlister** [comment]
Hi @Drosophilic - did we talk about this yesterday? I think we may have missed it out. What are your initial thoughts? Thanks!

**Comment by Drosophilic** [comment]
My initial thoughts are that Health Sciences should be somewhere near if not identical to Biomedical Sciences. If I understand the distinction correctly, Biomedical Science is the study of the process of a disease, and the research around treatment etc., and Health Science is the study of the disease and the patient treatment, so they are overlapping but sufficiently distinct. I suggest therefore that, until we involve discipline experts, we have both Biomedical Science and Health Science at the same level, under Medicine. Does that make sense? Do you have an alternative suggestion?

**Comment by allysonlister** [comment]
I agree this is the best way to go. Shall I switch this to a community consultation label and take it out of this point release milestone?

**Comment by allysonlister** [comment]
Hi @Drosophilic - as you can see in the log to this ticket, I got confused about this ticket as part of the COVID milestone. I noticed you added it to the COVID milestone a few weeks ago - do you want this resolved as part of the COVID work? Thanks!

**Comment by allysonlister** [comment]
@Drosophilic @delphinedauga and I decided on this hierarchy change.

Health Science
  - Biomedical Science (also a child of Biology)
  - Clinical Immunology

**Comment by allysonlister** [comment]
Here is the diff of this commit against the last commit of SRAO-merged.owl (please note this incorporates a few of the last tickets as well as this one):

# Ontology comparison

## Old
- Ontology IRI: `http://www.fairsharing.org/ontology/subject/SRAO.owl`
- Version IRI: *None*
- Loaded from: `file:/home/.../subject-ontology/development/SRAO-merged.owl`

## New
- Ontology IRI: `http://www.fairsharing.org/ontology/subject/SRAO.owl`
- Version IRI: *None*
- Loaded from: `file:/home/.../subject-ontology/development/build/SRAO-merged.owl`

### Ontology imports 



### Ontology annotations 



### Biomedical Science `http://purl.obolibrary.org/obo/NCIT_C15188`
#### Removed
- [Biomedical Science](http://purl.obolibrary.org/obo/NCIT_C15188) SubClassOf [Life Science](http://aims.fao.org/aos/agrovoc/c_4318) 

#### Added
- [Biomedical Science](http://purl.obolibrary.org/obo/NCIT_C15188) SubClassOf [Health Science](http://purl.obolibrary.org/obo/NCIT_C19199) 

- [Biomedical Science](http://purl.obolibrary.org/obo/NCIT_C15188) SubClassOf [Biology](http://purl.obolibrary.org/obo/NCIT_C16345) 


### SRAO_0000400 `http://www.fairsharing.org/ontology/SRAO_0000400`

#### Added
- [SRAO_0000400](http://www.fairsharing.org/ontology/SRAO_0000400) [label](http://www.w3.org/2000/01/rdf-schema#label) "Medical Virology"@en 

- [SRAO_0000400](http://www.fairsharing.org/ontology/SRAO_0000400) [hasRelatedSynonym](http://www.geneontology.org/formats/oboInOwl#hasRelatedSynonym) "Clinical Virology" 

- [SRAO_0000400](http://www.fairsharing.org/ontology/SRAO_0000400) [comment](http://www.w3.org/2000/01/rdf-schema#comment) "FAIRsharing requirement" 

- [SRAO_0000400](http://www.fairsharing.org/ontology/SRAO_0000400) [definition](http://purl.obolibrary.org/obo/IAO_0000115) "Medical Virology is the study of the diagnosis and management of infectious diseases from a clinical and laboratory perspective, with particular interest in infection control, medical microbiology and public health. [Adapted from Royal College of Pathologists https://www.rcpath.org/resourceLibrary/medical-virology-incorporating-cit-curriculum.html, AL 20.5.2020]" 

- Class: [SRAO_0000400](http://www.fairsharing.org/ontology/SRAO_0000400) 

- [SRAO_0000400](http://www.fairsharing.org/ontology/SRAO_0000400) SubClassOf [Medicine](http://purl.obolibrary.org/obo/OMIT_0009577) 

- [SRAO_0000400](http://www.fairsharing.org/ontology/SRAO_0000400) SubClassOf [Virology](http://edamontology.org/topic_0781) 


### hasRelatedSynonym `http://www.geneontology.org/formats/oboInOwl#hasRelatedSynonym`

#### Added
- AnnotationProperty: [hasRelatedSynonym](http://www.geneontology.org/formats/oboInOwl#hasRelatedSynonym) 

- [hasRelatedSynonym](http://www.geneontology.org/formats/oboInOwl#hasRelatedSynonym) SubPropertyOf: [alternative term](http://purl.obolibrary.org/obo/IAO_0000118)
