### ISSUE TITLE
difference between "Chemical biology" and BioChemistry"

### ISSUE THREAD

**Issue by only1chunts** [FAIRsharing/subject-ontology#35]
the terms both have definitions, but i'm still not clear on the distinction.
Chemical Biology - The use of synthetic chemistry to study and manipulate biological systems.
Biochemistry - Chemical substances and physico-chemical processes and that occur within living organisms.
The former sounds like it might be talking about chemical drugs, which I thought generally also came under the biochemistry heading. 
Just flagging this for a clarification in definition or merging of terms .

**Comment by Drosophilic** [comment]
Thanks @only1chunts, these are good points. We'll look into this and fix it for the 0.2 release.

**Comment by allysonlister** [comment]
Thanks again for the feedback @only1chunts. We've investigated the subjects and are happy that there is a significant difference in the two research areas (Chemical Biology has much more of a synthetic biology / chemical compounds focus, and Biochemistry deals with the chemistry of living systems). You are correct that Chemical Biology relates more about chemical compounds and as such does not need to be within the Biochemistry hierarchy. However, we did consider whether or not Chemical Biology might be a child of Pharmacology, but in the end did not add it to that hierarchy as Chemical Biology can deal with compounds that are not drugs.
 
As such, we are closing this ticket now, but please feel free to reopen it if you have any additional suggestions for changes in the hierarchy or annotation. Thanks very much!
