### ISSUE TITLE
metagenomics topics

### ISSUE THREAD

**Issue by only1chunts** [FAIRsharing/subject-ontology#36]
not sure how deep you want to go for metagenomics type topics, but this paper gives some good definitions of terms that might be appropriate (some you already have):
https://microbiomejournal.biomedcentral.com/articles/10.1186/s40168-015-0094-5
e.g.
Metataxonomics
Metagenome
Microbiome
Metabolomics
Metabonomics
Metatranscriptomics
Metaproteomics

**Comment by Drosophilic** [comment]
Thanks @only1chunts for your comment and the links. Unfortunately, this hasn't made it into SRAO 0.2 but we'll look into this for the 0.3 release.

**Comment by allysonlister** [comment]
Metataxonomics: added at http://www.fairsharing.org/ontology/subject/SRAO_0000403
Metagenome: remains as Metagenomics, unchanged at http://edamontology.org/topic_3174
Microbiome: not in scope for SRAO, already in DRAO as http://www.ebi.ac.uk/efo/EFO_0004982
Metabolomics: already present at http://edamontology.org/topic_3172
Metabonomics: currently a synonym of topic_3172, and therefore we will wait to add this as there isn't a great need for this term at this stage. If we need it later, we would have to disambiguate the EDAM class or just drop the use of the EDAM IRI and create our own pair of classes.
Metatranscriptomics: currently a synonym of an EDAM class http://edamontology.org/topic_3308. We won't have this synonym in the next release as it isn't a true synonym, but will not add this term at this time for the same reasons as Metabonomics:  If we need it later, we would have to disambiguate the EDAM class or just drop the use of the EDAM IRI and create our own pair of classes.
Metaproteomics: added at http://www.fairsharing.org/ontology/subject/SRAO_0000404

Please let us know if you would like to revisit any of these decisions. Thanks!

**Comment by only1chunts** [comment]
I'm fine with all those actions, but I would point out that metatranscriptomics is quite prevalent, and as you say it's not a true synonym of transcriptomics. I can envisage that term being required very soon, in fact, we already have 3 published datasets on the subject, so if the term was included we would probably make use of it, we are currently using both metagenomics and transcriptomics as the subjects, but include the word metatranscriptomics as a keyword, e.g. http://dx.doi.org/10.5524/100151

**Comment by allysonlister** [comment]
Thanks very much - this is a very good point. Seeing as you are already using it, then I think it makes sense to disambiguate and make two terms, dropping the EDAM IRI in the process (http://edamontology.org/topic_3308). I'll comment again once it's done.

**Comment by allysonlister** [comment]
In fact, between the last EDAM release we pulled and the current one, they have disambiguated these terms themselves. Therefore we will retain:

http://edamontology.org/topic_3308: transcriptomics
http://edamontology.org/topic_3941: metatranscriptomics
