### ISSUE TITLE
"Environmental Science" / "Ecology"

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/subject-ontology#4]
Our production server currently has both "Environmental Science" and "Ecology". SRAO just has Ecology, which comes from EDAM, and its alternative terms:

![ecology](https://user-images.githubusercontent.com/143586/40480039-365921b6-5f45-11e8-8628-2e9a90804761.png)

As much as I'd like to use EDAM, I feel that 

1. The synonyms used by EDAM are overloaded - there are too many research disciplines thrown into this particular class, and
2. Environmental Science is only mentioned in the definition, not as an alternative term.

As I see it, we have two options for modelling this in SRAO:

1. Keep things as they are, and add Environmental Science as a synonym of our existing SRAO "Ecology" class, or
2. Make a second class, and restructure Ecology so its definition is clearer. Such a thing would look like:

Environmental Science, from AgroVoc: http://aims.fao.org/aos/agrovoc/c_331559
-and-
Ecology, from NCIT: http://purl.obolibrary.org/obo/NCIT_C16526 

I vote for option number 2, as it seems these are two different discplines. If we go with it, here's my suggested hierarchy:

NCIT has Ecology as a child of Biology, just as we have it now in SRAO. It should be noted that in OMIT, Ecology is a child of both Biology and Earth Sciences. I think Ecology should stay as it is in the hierarchy, and environmental science should be a sibling, which has an addition parent of Earth Sciences.

For evidence for number 2, see:

https://blog.oup.com/2012/05/its-ecology-not-environmental-science/ : "Ecology is the “branch of biology that deals with the relations of organisms to one another and to their physical surroundings,” and was coined as “oekologie” by the German biologist Ernst Heackel in the 19th century from the Greek oikos meaning “house” and ology “the study of”. Ecology is, literally, the study of where living organisms live. By contrast, Environmental Science is a broader, interdisciplinary field in which ecologists work with other physical, chemical, and biological “ologists” to study and seek solutions to environmental problems. It’s a fine line between the two, but one role of ecology is to inform environmental science."

https://www.quora.com/What-are-the-main-differences-between-ecology-and-environmental-science 

Thoughts?

**Comment by Drosophilic** [comment]
I vote for option 2 too. Ecology != Environmental science.
Thanks!
