### ISSUE TITLE
Placement of Bioinformatics

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/subject-ontology#41]
The following comment is outstanding within SRAO, so have moved it to the tracker and removed it from the owl file.

Should 'Informatics'->'Bioinformatics' be under 'Engineering Science' rather than 'Life Sciences'? PAM 27.02.2018

**Comment by Drosophilic** [comment]
Although I wrote that comment over a year ago, I still think it has value. Would it make sense to add 'Informatics'->'Bioinformatics' under both Computer Science and Life Science?

**Comment by allysonlister** [comment]
I hadn't added in this comment the current parents of the class - my mistake. Bioinformatics has two parents at the moment - Informatics (child of computer science -> engineering science) and Biology.

Is this sufficient to close this ticket @Drosophilic ? :)
