### ISSUE TITLE
Removal of 'FAIRsharing alternative term' from Veterinary Medicine

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/subject-ontology#46]
topic_3397 in SRAO is Veterinary Medicine. We currently are using the 'FAIRsharing alternative term' property within this class to provide the 'Veterinary Science' synonym. I should check with @Drosophilic as to which label he would prefer, and then ensure the other one is labelled as either a standard 'alternative term' or an 'EDAM alternative term', as appropriate.

This was brought to my attention via this issue: https://github.com/FAIRsharing/FAIRsharing-API/issues/68

**Comment by Drosophilic** [comment]
I would suggest 'Veterinary Science' as an 'alternative term', thanks.
