### ISSUE TITLE
COVID-19 

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/subject-ontology#51]
We currently have a user-defined tag 'COVID-19' to use for records in FAIRsharing that relate to that area of work. The question is this: are we modelling the virus (and therefore this is a taxonomy issue and not a DRAO/SRAO issue) or something else, such as the research/subject area? If it's the latter, we may wish to put it into SRAO and perhaps make it a child of Virology. If this is the way you want to go, I can look into existing ontologies and see if there's an appropriate term, otherwise we'll have to mint a SRAO IRI.

**Comment by Drosophilic** [comment]
So the virus is 'Sars-CoV-2' and the disease it causes is 'Covid-19'. We therefore are not modelling the virus (we already have 'Coronaviridae' as a species), but the domain area, with some resources having virus RNA sequences, others having patient data, so this user tag cuts across subjects and domains. 

At the moment, I think 'COVID-19' should remain a user tag. I don't envisage it joining either SRAO or DRAO at the present time.

**Comment by allysonlister** [comment]
That makes sense. I'll go ahead and close this/ Thanks @Drosophilic !
