### ISSUE TITLE
Respiratory Medicine

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/subject-ontology#52]
As part of #49 we would like to add Respiratory Disease. 

I suggest that we add this to SRAO as "Resipratory Research". There is no such term in OLS at the moment, although there is "Respiratory Medicine" (http://edamontology.org/topic_3322) which I think is a different situation, and I'm not sure about the use of topic_3322 at the moment.

Respiratory Research seems to be a term heavily used by a number of journals, incl BMJ Open Respiratory Research and BMC Respiratory Research. I can have a look for an appropriate definition if we go this route, though we'll likely have to mint an IRI. 

Alternatively we could keep it as Respiratory Disease, and then move this ticket to DRAO. There is precedent, as we already have things like cardiovascular disease in DRAO (but also cardiology in SRAO ;-) so there is precendent for both).

Let me know which you'd prefer.

**Comment by allysonlister** [comment]
@Drosophilic has suggested in #49 that "For Respiratory Disease, I would suggest this goes under Medicine as 'Respiratory Medicine'." I will look into definitions / IRIs next for this term.

**Comment by allysonlister** [comment]
Respiratory Research and Respiratory Medicine are only near synonyms, not exact synonyms. To align with how we already have Tropical Medicine, we should go with Respiratory Medicine, agreed with @Drosophilic with Delphine.

**Comment by allysonlister** [comment]
There are three major choices within existing ontologies for these terms: NCIT, OMIT, and EDAM. Whichever we choose, we will place it under 'Medicine'.

1. NCIT: listed as '[Pulmonary Medicine](https://www.ebi.ac.uk/ols/ontologies/ncit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_C105692)' (http://purl.obolibrary.org/obo/NCIT_C105692). This is an appropriate exact synonym or Respiratory Medicine and I'd be happy to use it. Definition is good. This is my first choice.

2. OMIT: also listed as '[Pulmonary Medicine](https://www.ebi.ac.uk/ols/ontologies/omit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FOMIT_0016058)' (http://purl.obolibrary.org/obo/OMIT_0016058), but with no definition. I suggest not using this due to a lack of definition.

3. EDAM: is the only OLS ontology with '[Respiratory Medicine](https://www.ebi.ac.uk/ols/ontologies/edam/terms?iri=http%3A%2F%2Fedamontology.org%2Ftopic_3322)' (http://edamontology.org/topic_3322) as the primary label, but NCIT's label is useful anyway. We already use EDAM's [Tropical Medicine](https://www.ebi.ac.uk/ols/ontologies/edam/terms?iri=http%3A%2F%2Fedamontology.org%2Ftopic_3575) term, but as with Tropical Medicine (whose definition seems limited and not strictly matching the term), I am less enamoured of its synonyms: Pulmonology, Pulmonary medicine, Respiratory disease, Pulmonary disorders. After all, 'Respiratory Medicine' is not a synonym for a disorder or disease.

I suggest either 1 (preferred) or 3. If we progress with using the EDAM term, I could raise a ticket each with EDAM for both terms.

There's always the option to mint our own IRI, but I don't think we'll need to in this case.

**Comment by delphinedauga** [comment]
1 also

**Comment by allysonlister** [comment]
Perfect! I'm ready to add this. Will close when completed - thanks!
