### ISSUE TITLE
Earth science specific terms

### ISSUE THREAD

**Issue by delphinedauga** [FAIRsharing/subject-ontology#53]
- “Selenography”

**Synonym:** Lunar science
**Definition:** “Selenography is the study of the surface and physical features of the Moon.” [WIKIPEDIA]
**Related record:** EUROLAS Data Center, https://fairsharing.org/biodbcore-001482/ 
**Where in the hierarchy:** part_of “Astrophysics and Astronomy”

- “Ionosphere studies”

**Definition:** Studies of the ionosphere. “The ionosphere is a layer of the Earth's atmosphere which extends from about 60 to 1,000 kilometers above the planetary surface and is ionised by solar radiation. It includes the thermosphere and parts of the mesosphere and exosphere.” [Environment Ontology] https://bioportal.bioontology.org/ontologies/ENVO?p=classes&conceptid=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FENVO_01000545
**Related record:** World Data Centre for Space Weather, https://fairsharing.org/biodbcore-001477/
**Where in the hierarchy:** part_of “Atmospheric Science”
**Comments:** Not clear to me if this term should be in SRAO or in DRAO. Already defined in “User-defined Tags”

- “Cosmology”

**Definition:** “Cosmology is a branch of astronomy concerned with the studies of the origin and evolution of the universe, from the Big Bang to today and on into the future.” [WIKIPEDIA] 
https://en.wikipedia.org/wiki/Cosmology
**Related record:** World Data Centre for Space Weather,	https://fairsharing.org/biodbcore-001477/
**Where in the hierarchy:** part_of “Astrophysics and Astronomy”

- “Electromagnetism”

**Definition:** “Electromagnetism is a branch of physics involving the study of the electromagnetic force, a type of physical interaction that occurs between electrically charged particles.” [WIKIPEDIA] https://en.wikipedia.org/wiki/Electromagnetism
**Related record:** World Data Centre for Space Weather, https://fairsharing.org/biodbcore-001477/
**Where in the hierarchy:** part_of “Physics”

- “Gemology”

**Definition:** “Gemology or gemmology is the science dealing with natural and artificial gemstone materials. It is considered a geoscience and a branch of mineralogy.” [WIKIPEDIA] 
https://en.wikipedia.org/wiki/Gemology
**Related record:** RRUFF Project, https://fairsharing.org/biodbcore-001486/
**Where in the hierarchy:** part_of “Mineralogy”

- “Geomagnetism”

**Definition:** “Earth's magnetic field, also known as the geomagnetic field, is the magnetic field that extends from the Earth's interior out into space, where it interacts with the solar wind, a stream of charged particles emanating from the Sun.” [WIKIPEDIA] 
https://en.wikipedia.org/wiki/Earth%27s_magnetic_field
**Synonym:** Earth's magnetic field
**Related record:** https://fairsharing.org/biodbcore-001555/
**Where in the hierarchy:** part_of “Geophysics”

- “Bathymetry”

**Definition:** “Bathymetry (/bəˈθɪmətriː/) is the study of underwater depth of ocean floors or lake floors.” [WIKIPEDIA] 
https://en.wikipedia.org/wiki/Bathymetry
**Related record:** https://fairsharing.org/FAIRsharing.88wme4
**Where in the hierarchy:** part_of ?

- “Hydrography”

**Definition:** “Hydrography is the branch of applied sciences which deals with the measurement and description of the physical features of oceans, seas, coastal areas, lakes and rivers, as well as with the prediction of their change over time, for the primary purpose of safety of navigation and in support of all other marine activities, including economic development, security and defense, scientific research, and environmental protection.” [WIKIPEDIA] 
https://en.wikipedia.org/wiki/Hydrography
**Related record:** https://fairsharing.org/biodbcore-001599/
**Where in the hierarchy:** part_of ?

**Comment by allysonlister** [comment]
Thanks! I'll take a look after I do the COVID stuff. Happy to have you add as many as you think are relevant here, and when it's time, I'll look at them all. :)

**Comment by allysonlister** [comment]
Selenography http://www.fairsharing.org/ontology/subject/SRAO_0000406
Cosmology http://www.fairsharing.org/ontology/subject/SRAO_0000407
Electromagnetism http://www.fairsharing.org/ontology/subject/SRAO_0000408
gemology: http://www.fairsharing.org/ontology/subject/SRAO_0000409
Bathymetry: child of hydrography and Oceanography. http://www.fairsharing.org/ontology/subject/SRAO_0000410
hydrography: http://www.fairsharing.org/ontology/subject/SRAO_0000411

I'm not sure how Ionosphere studies fits in, however... I think atmospheric science will cover this, and we already have this term?

**Comment by allysonlister** [comment]
@delphinedauga I'll leave this ticket for you to close once you've completed the FAIRsharing curation, after this release is imported.

**Comment by allysonlister** [comment]
I'm going to revisit my prior comment @delphinedauga - I see that you had already added the user-defined tag, and these will get overwritten by the subject tags, so we can close this ticket. Feel free to double-check these records once the release is imported into FAIRsharing.
