### ISSUE TITLE
Medical Virology

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/subject-ontology#54]
After discussion with @delphinedauga  and @Drosophilic, we have decided to add Medical Virology (with parents Virology and Medicine), and a near synonym of Clinical Virology. Please note that the new FAIRsharing system does not yet know about near synonyms, only exact synonyms.

_Originally posted by @allysonlister in https://github.com/FAIRsharing/subject-ontology/issues/49#issuecomment-622318835_

**Comment by allysonlister** [comment]
To bring our full discussion from our original summary thread, here is a comment by @delphinedauga which clarifies why we don't want 'Clinical Virology' as an exact synonym.

I agree with Ally

    « Medical virology » could be used as the same model as « medical microbiology » (The study of microorganisms with an emphasis on their role in the human disease process) : The study of virus with an emphasis on their role in the human disease process.

> I found 1 definition for « clinical virology » :
> 
>  A subdiscipline of virology focusing on aspects of human virology that directly pertains to virus-induced clinical conditions, including epidemiology, pathogenesis, diagnosis and detection, and prevention and treatment (National Cancer Institute Thesaurus (NCIT))
> 
> Quite difficult to me to make a difference between « medical » & « clinical » and I think the definition below is wrong.
> 
> Clinical : Relating to the examination and treatment of patients dependent on direct observation. The term may also refer to the institution (clinic) providing this activity (National Cancer Institute Thesaurus (NCIT))
>  Medical : Relating to the study or practice of medicine (National Cancer Institute Thesaurus (NCIT))
> 
> « Clinical » is more specific compared to « medical ». I would use « medical virology » instead of « clinical virology », because « medical virology » will include the examination and treatment of patients dependent on direct observation but also potential treatment studies and prevention.

**Comment by allysonlister** [comment]
While NCIT has [Molecular Virology](https://www.ebi.ac.uk/ols/ontologies/ncit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_C18887) and [Clinical Virology](https://www.ebi.ac.uk/ols/ontologies/ncit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_C18708) (child of Clinical Microbiology and also of Virology), it does not have 'Medical Virology', and no other OLS / BioPortal / AgroVoc (I know - but the agriculture resource has lots of biomedical terms too) ontologies have anything close (other than the much more generic 'Virology' that we already have in SRAO (taken from EDAM).

Therefore I see two choices: either make use of 'Clinical Virology' instead, or look further afield for a class describing 'Medical Virology'.

If we wish to look further afield, here are some definitions, though I haven't found any ontology classes describing it yet (these are rough definitions - I can apply our style conventions once we decide what route we wish to take):

1. [Journal of Medical Virology](https://onlinelibrary.wiley.com/page/journal/10969071/homepage/forauthors.html): "fundamental as well as applied research concerning viruses affecting humans. These include [...] the characterisation, diagnosis, epidemiology, immunology and pathogenesis of human virus infection, as well as basic studies on virus morphology, genetics, replication and host-cell interactions."
2.  [Royal College of Pathologists](https://www.rcpath.org/resourceLibrary/medical-virology-incorporating-cit-curriculum.html): "[...] the diagnosis and management of infectious disease from a clinical and laboratory perspective [... including specialist areas of medical virology including ]   infection control, medical microbiology and public health".

The definitions are limited in Google, but I may be missing something - happy for other suggestions, otherwise I suggest we mint an IRI and use a slightly modified version of definition number 1 above, and the previously-agreed upon parent classes of Virology and Medicine.

**Comment by delphinedauga** [comment]
I would prefer the second choice, using and describing 'Medical Virology'. 

Concerning the definition, the second is a little more appropriate. 
In the first definition, it is mentioned that 'medical virology' is also "basic studies on virus morphology, genetics, replication and host-cell interactions". But for me this is 'virology'. The second definition is more science applied to medicine.

**Comment by allysonlister** [comment]
Thanks @delphinedauga - to refine your preferred definition slightly (from  [Royal College of Pathologists](https://www.rcpath.org/resourceLibrary/medical-virology-incorporating-cit-curriculum.html)), how about this?

**definition**: Medical Virology is the study of the diagnosis and management of infectious diseases from a clinical and laboratory perspective, with particular interest in infection control, medical microbiology and public health. [Adapted from Royal College of Pathologists https://www.rcpath.org/resourceLibrary/medical-virology-incorporating-cit-curriculum.html, AL 20.5.2020]
**hierarchy**: parents will be 'Virology' and 'Medicine'
**near synonym**: Clinical Virology. _please note that this term will not be visible on either the old or new FAIRsharing site as things stand, as this type of synonym has not been in SRAO prior to this ticket._

Shall I proceed with this, @Drosophilic and @delphinedauga ?

**Comment by delphinedauga** [comment]
Perfect !

**Comment by allysonlister** [comment]
If people agree, I would suggest that the best annotation property to provide us with a "near" synonym would be GO's "related" synonyms. Details are at http://geneontology.org/docs/GO-term-elements, and the related synonyms are defined as 

> the terms are related in some imprecise way; for e.g. cytochrome bc1 complex is a related synonym of ubiquinol-cytochrome-c reductase activity virulence is a related synonym of pathogenesis

That would mean me adding the IRI (http://www.geneontology.org/formats/oboInOwl#hasRelatedSynonym) and label for RelatedSynonym to SRAO before @delphinedauga progresses with this ticket. @Drosophilic please would you let us know if you agree with 1) our choices for definition/related synonym/hierarchy/label, and 2) with my choice of IRI for related synonym in general.

Please note that FAIRsharing is unaware of RelatedSynonyms, and will ignore them, both in the new and old systems unless we create tickets.

Thanks! :)

**Comment by Drosophilic** [comment]
Amazing! (Yes, I agree)

**Comment by allysonlister** [comment]
Ready for @delphinedauga to take over, or alternatively let me know and I can finish this. :) thanks!
