### ISSUE TITLE
Archaeology

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/subject-ontology#55]
https://fairsharing.org/biodbcore-001484/ has added Archaeology as a UDT, and I can see why. We currently have many different subtypes of Archaeology within the Ancient Cultures hierarchy, but no overarching term, which I think is required as the subdisciplines we have listed (even if we add more) will never be comprehensive. 

Either 'Ancient Cultures' can be modified or, as a better solution, I recommend that we add Archaeology in an appropriate location. MESH has Archaeology as a child of 'Cultural Anthropology'... I think we may wish to take a look at the 'Ancient Cultures' and 'Anthropology' hierarchies, perhaps asking a domain expert, and maybe adjust accordingly as part of this work. This hierarchy may benefit from a second look more generally.

Here is part of the Humanities hierarchy, as relevant to this discussion:
![partial-humanities](https://user-images.githubusercontent.com/143586/81540544-b7a34080-9369-11ea-8ccd-c5b4b57c4082.png)

**Comment by delphinedauga** [comment]
It seems that "archaeology" isn't just about ancient cultures.
Here a definition from MESH : "Study of the ancient and recent human or animal past through material remains. It analyzes the physical remains of the past in pursuit of a broad and comprehensive understanding of human culture."
https://bioportal.bioontology.org/ontologies/MESH?p=classes&conceptid=http%3A%2F%2Fpurl.bioontology.org%2Fontology%2FMESH%2FD001106

Wikipedia says that it is part_of "humanities" : Archaeology, or archeology,[1] is the study of human activity through the recovery and analysis of material culture. The archaeological record consists of artifacts, architecture, biofacts or ecofacts and cultural landscapes. Archaeology can be considered both a social science and a branch of the humanities
https://en.wikipedia.org/wiki/Archaeology

**Comment by allysonlister** [comment]
Thanks @delphinedauga . Sounds like we're thinking along the same lines.

As such, I recommend the following change:

### Archaeology
**Hierarchy:** added as a child of Cultural Anthropology, in line with MeSH / OMIT. Use the OMIT term (http://purl.obolibrary.org/obo/OMIT_000249) [as described in OLS](https://www.ebi.ac.uk/ols/ontologies/omit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FOMIT_0002494). Cultural Anthropology is already a child of Humanities, so this also fits with the Wikipedia description.

**Definition** : MeSH definition as listed by @delphinedauga (see https://meshb.nlm.nih.gov/record/ui?ui=D001106)

**IRI**: OMIT IRI, perhaps with an appropriate annotation property referencing the MeSH identifier (https://id.nlm.nih.gov/mesh/D001106.html). However, if we do this last thing (which I think is appropriate), we would need a separate ticket as all OMIT terms derived from MeSH should be similarly attributed.

### Classical Archaeology
**Current definition and placement**: Classical Archaeology is the archaeological investigation of the Mediterranean civilizations of Ancient Greece and Ancient Rome. [Wikipedia https://en.wikipedia.org/wiki/Classical_archaeology, AL 13.6.2019]. Child of Ancient Cultures
**Suggested modification**: Add 'Archaeology' as an additional parent term of 'Classical Archaeology' but otherwise leave this class as is.

@Drosophilic are you OK with me progressing on these two modifications (addition of 'Archaeology', update to 'Classical Archaeology'?) Additionally, should we add the IRIs for the underlying MeSH terms where OMIT has pulled the MeSH hierarchy, and then subsequently we have used the MeSH term?

Thanks :)

**Comment by Drosophilic** [comment]
Please go ahead, thanks both.

**Comment by Drosophilic** [comment]
Note - we'll need to retrofit the data in FAIRsharing.

**Comment by allysonlister** [comment]
Thanks - shall I link it to the next milestone (0.2.1)?

**Comment by allysonlister** [comment]
Please note that http://purl.obolibrary.org/obo/OMIT_0002494 (Archaeology) is represented within SRAO as "Classical Archaeology". This is a mistake, as we should have created this class specifically as Archaeology. The 9 records tagged with this term are good for the use of Archaeology instead, so this ticket has turned into an update of the annotation and labelling to match what OMIT has for http://purl.obolibrary.org/obo/OMIT_0002494.

No need for an additional term.
