### ISSUE TITLE
Infectious Disease Medicine

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/subject-ontology#56]
A new term as part of the work generated from ticket #49.

**Comment by allysonlister** [comment]
@Drosophilic has stated in #49 that 'Infectious Disease Medicine', from his perspective, is a subject area concerning the diseases themselves and their progression in an individual (as opposed to a population).

This term is in contrast to ['Infectology' / 'infectious disease'](https://github.com/FAIRsharing/domain-ontology/issues/57), a term we plan to add to DRAO and that concerns the disorder itself, rather than research into that topic. 

As such, here is my proposal

**Comment by delphinedauga** [comment]
Sounds good to me

**Comment by allysonlister** [comment]
Pete has completed his changes. Closing the ticket. :-)
