### ISSUE TITLE
Drug Repositioning

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/subject-ontology#57]
'Drug Repositioning' is being promoted from a user-defined term (UDT) to a SRAO class,  as a sibling class of 'Drug Development'. 

_Originally posted by @allysonlister in https://github.com/FAIRsharing/domain-ontology/issues/55#issuecomment-631444435_

**Comment by allysonlister** [comment]
### Definition
Drug repositioning is the deliberate and methodical practice of finding new applications for existing drugs. [Adapted from MeSH https://meshb.nlm.nih.gov/record/ui?ui=D058492, AL 20.5.2020]

### Hierarchy
Although the MESH hierarchy lists this class as a child term of 'Drug Development', which we have as a subject in SRAO, it was agreed with @Drosophilic  and @delphinedauga that we should create it as a sibling class of 'Drug Development' as this more closely matches the defintions.
![dd](https://user-images.githubusercontent.com/143586/82447481-461d6d80-9aa0-11ea-953d-4e8e51fcad37.png)

### IRI
http://purl.obolibrary.org/obo/OMIT_0027237

Please would both @Drosophilic and @delphinedauga let me know if they're OK with this? Thanks!

**Comment by delphinedauga** [comment]
Agree !

**Comment by allysonlister** [comment]
Great job @delphinedauga, and thanks for completing this ticket! :)
