### ISSUE TITLE
Veterinary Medicine / Basic Veterinary Medical Science

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/subject-ontology#6]
SRAO contains 'Basic Veterinary Medical Science' (from re3data) which is linked to the EDAM term topic_3397. This class has a label of 'Veterinary Medicine', which we've retained in SRAO as an alternative term. A user has now added the tag 'Veterinary Science' to https://fairsharing.org/biodbcore-001091/ . I think our users will find 'Veterinary Medicine' more useful than 'Basic Veterinary Medical Science' as a label. Therefore I suggest that we:

1. Move 'Basic Veterinary Medical Science' to be a re3data alternative term
2. Make 'Veterinary Medicine' the primary label. 
3. Add a new parent 'Medicine' to 'Veterinary Medicine' (in addition to it's current placement as a child of Agriculture, which comes from re3data).
4. Add an additional alternative label of 'Veterinary Science' to help users find this tag in future.

What do people think? Thanks!

**Comment by Drosophilic** [comment]
My only comment would be to query the medicine-> veterinary medicine, as really they should be equivalent, rather than parent-child, unless we have a human medicine term.

**Comment by allysonlister** [comment]
You make a good point, and indeed the current definition of Medicine does not mention any particular species: "Research in support of healing by diagnosis, treatment, and prevention of disease.". This definition and IRI for Medicine comes from EDAM, which then has Veterinary Medicine as a child term, so in that regard, we would be aligning with the underlying hierarchy of the EDAM terms we're using. And indeed there are a large number of specialisms of Medicine within the SRAO hierarchy.

In the same way that something like Geriatric Medicine or Dermatology are children of Medicine, wouldn't Veterinary Medicine be an appropriate specialism / child term?

I'm not tied to any particular solution, but equally I know that our users are requesting some variant of Veterinary Medicine...

**Comment by allysonlister** [comment]
Pete confirmed during curation call that we can go ahead with Veterinary Medicine as a child of Medicine, and I will now make all changes listed in the original comment.
