### ISSUE TITLE
Formatting tidying

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/subject-ontology#63]
To pull accurate statistics from SRAO it would be helpful to add language "en" to all uses of IAO_0000412 (imported from) so that they compare as the same when running queries, e.g. SPARQL queries. Most already have this but a few are missing.

This will not affect the hierarchies or any other properties.

**Comment by Drosophilic** [comment]
Shouldn't take too long. Shouldn't we do the same with DRAO?

**Comment by allysonlister** [comment]
I can check DRAO at the same time, but as SRAO is manually updated, those are the times when human error creeps in. 

Please note I seem to have done this in the past, via `development/sparql/importedfrom-en.ru` - so running this / modifying this should help us automate the work. I can create a matching ticket in DRAO.

**Comment by allysonlister** [comment]
I have made a related ticket for the manual terms in DRAO, as those are likely the only ones that we would have the issue with: https://github.com/FAIRsharing/domain-ontology/issues/80

**Comment by allysonlister** [comment]
This is currently not necessary as these statements will be handled by the ODK, but as part of that command is not yet working, we can close this particular ticket for now and make a new one once the particular modifications are working.
