### ISSUE TITLE
Botany versus Horticulture

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/subject-ontology#7]
A user has added Horticulture. We already have Botany and its children

![botany](https://user-images.githubusercontent.com/143586/41407640-ec55d698-6fc7-11e8-9f2d-1bad0818875f.png)

However, it does seem as if the two terms are not synonymous, e.g. "Botany is regarded as a broader, pure science in regards to living plant organisms, from the smallest bacteria to the largest trees. Horticulture, on the other hand, is an applied science under that umbrella and focuses solely on edible and ornamental plant life. (https://horticulture.cals.ncsu.edu/online/botany-vs-horticulture/)

The questions are:

1. Shall we add Horticulture? I think so. Like Agriculture, it is an applied science. Our original label for Agriculture (still present as a re3data alternative term) includes "Horticulture".
2. Placement: child of Agriculture. I don't think it should also be a child of Botany, but happy to be swayed.
3. IRI: http://aims.fao.org/aos/agrovoc/c_3671 (AgroVoc)
4. definition: "The cultivation of a garden; the art or science of cultivating or managing gardens, including the growing of flowers, fruits, and vegetables. [Oxford English Dictionary]"

thanks all!

**Comment by Drosophilic** [comment]
All sounds good. I agree shouldn't be a child of botany.
