### ISSUE TITLE
'Computational Materials Science' and 'Materials Informatics'

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/subject-ontology#8]
Source: https://fairsharing.org/biodbcore-001089/

We have Materials Science already as follows
![materials](https://user-images.githubusercontent.com/143586/41849616-723d08a8-7879-11e8-8c98-00390c230df1.png)

Our user has suggested 'Computational Materials Science' and 'Materials Informatics' in addition to what already exists. Both of these terms seem to be broadly referring to the same subject - a computational sub-category of Materials Science. Most of the online defs for Computational Materials Science seem to focus on computational models to aid in the development and improvement of new and existing materials. Definitions for Materials Informatics seem broadly similar, though also seem to be generally broader, including all types of informatics and not just modelling.

What are your thoughts? Should we include both, neither, one of them? Thanks!

**Comment by allysonlister** [comment]
What would you like to do for this, @Drosophilic ? Thanks!

**Comment by Drosophilic** [comment]
I don't think we should put both, as that may be too specific. I suggest we use the broader 'Materials Informatics' term for now.

**Comment by allysonlister** [comment]
Adding Materials Informatics with a definition "Materials informatics employs techniques, tools, and theories drawn from the emerging fields of data science, internet, computer science and engineering, and digital technologies to the materials science and engineering to accelerate materials, products and manufacturing innovations. " sourced from https://doi.org/10.1007/s10845-018-1392-0. It has two parents: Informatics and Materials Science.
